utils::globalVariables(c(
  # generic tidy-eval
  ".data",
  "all",
  "where",
  # panel / coding
  "country",
  "cow",
  "cowcode",
  "end_year",
  "gw",
  "gwcode",
  "microstate",
  "n",
  "name",
  "year",
  # GDP
  "gdp_growth",
  "gdp_pcap",
  "log_gdp_pcap",
  # conflict (legacy)
  "n_campaigns",
  # leader data
  "birthyear",
  "ccode",
  "enddate",
  "entry",
  "exit",
  "eyear",
  "female_leader",
  "gender",
  "gender_int",
  "irregular_entry",
  "irregular_exit",
  "leader",
  "leader_tenure",
  "military_bg",
  "militarycareer",
  "posttenurefate",
  "smonth",
  "start_ym",
  "startdate",
  "start_yr",
  "end_yr",
  "syear",
  "yrborn",
  # SCAD columns
  "cgovtarget",
  "escalation",
  "etype",
  "female_event",
  "lgbtq_issue",
  "lgtbq_issue",
  "ndeath",
  "npart",
  "rgovtarget",
  "repress",
  "styr",
  # UCDP/PRIO + VPP columns
  "cumulative_intensity",
  "ep_end",
  "gwno_loc",
  "incompatibility",
  "incompatibility_num",
  "intensity",
  "intensity_level",
  "region",
  "region_id",
  "type_of_conflict",
  # UCDP VPP raw column names (from xlsx)
  "GWNOLoc",
  "Incompatibility",
  "Intensity",
  "Year",
  # mmALL columns
  "protest",
  "protestnumber",
  "protesterviolence",
  "participants",
  "participants_category",
  "protesteridentity",
  "protesterdemand1",
  "protesterdemand2",
  "protesterdemand3",
  "protesterdemand4",
  "stateresponse1",
  "stateresponse2",
  "stateresponse3",
  "stateresponse4",
  "stateresponse5",
  "stateresponse6",
  "stateresponse7",
  # MMAD columns
  "cowcode",
  "event_date",
  "max_partviolence",
  "max_scope",
  "max_secengagement",
  "mean_avg_numparticipants",
  "numreports",
  "side"
))
